### Decision Tree

>classification algorithms

>it follows tree like structure to predict the output

><img src="https://miro.medium.com/v2/resize:fit:1430/1*rSQIIAboJftqAv_BReNipg.png">

In [69]:
import pandas as pd
import numpy as np

In [70]:
! pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\klegd\desktop\cc(ml) iii sem\.venv\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\klegd\desktop\cc(ml) iii sem\.venv\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [71]:
df = pd.read_excel(r"C:\Users\klegd\Desktop\CC(ML) III Sem\tennis_anyone_1000.xlsx")

In [72]:
df.head()

  Day ID   Outlook Temperature Humidity    Wind Play Tennis
0  Day_1  Overcast        Cool   Normal  Strong         Yes
1  Day_2      Rain        Mild     High    Weak         Yes
2  Day_3  Overcast         Hot   Normal    Weak         Yes
3  Day_4     Sunny        Mild   Normal  Strong         Yes
4  Day_5     Sunny        Mild     High    Weak          No

In [73]:
df.columns

Index(['Day ID', 'Outlook', 'Temperature', 'Humidity', 'Wind', 'Play Tennis'], dtype='str')

In [74]:
df.drop(columns='Day ID')

      Outlook Temperature Humidity    Wind Play Tennis
0    Overcast        Cool   Normal  Strong         Yes
1        Rain        Mild     High    Weak         Yes
2    Overcast         Hot   Normal    Weak         Yes
3       Sunny        Mild   Normal  Strong         Yes
4       Sunny        Mild     High    Weak          No
..        ...         ...      ...     ...         ...
995     Sunny        Mild     High    Weak          No
996  Overcast        Mild     High  Strong         Yes
997      Rain        Mild     High  Strong          No
998  Overcast        Cool   Normal  Strong         Yes
999      Rain        Mild   Normal    Weak         Yes

[1000 rows x 5 columns]

In [75]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Outlook']=le.fit_transform(df['Outlook'])
df['Temperature']=le.fit_transform(df['Temperature'])
df['Humidity']=le.fit_transform(df['Humidity'])
df['Wind']=le.fit_transform(df['Wind'])
df['Play Tennis']=le.fit_transform(df['Play Tennis'])

In [76]:
df.head()

  Day ID  Outlook  Temperature  Humidity  Wind  Play Tennis
0  Day_1        0            0         1     0            1
1  Day_2        1            2         0     1            1
2  Day_3        0            1         1     1            1
3  Day_4        2            2         1     0            1
4  Day_5        2            2         0     1            0

In [77]:
### How to check nuymber of yes and no's
df['Play Tennis'].value_counts()

Play Tennis
1    651
0    349
Name: count, dtype: int64

In [78]:
### Renaming the columns
df.rename(columns={'Play Tennis':'PlayTennis'},inplace=True)

In [79]:
df.head()

  Day ID  Outlook  Temperature  Humidity  Wind  PlayTennis
0  Day_1        0            0         1     0           1
1  Day_2        1            2         0     1           1
2  Day_3        0            1         1     1           1
3  Day_4        2            2         1     0           1
4  Day_5        2            2         0     1           0

In [80]:
df.shape

(1000, 6)

In [81]:
### Splitting dataset vertically (Input/Output)
x= df.iloc[:,0:-1]
y= df.iloc[:,-1]

In [82]:
x

       Day ID  Outlook  Temperature  Humidity  Wind
0       Day_1        0            0         1     0
1       Day_2        1            2         0     1
2       Day_3        0            1         1     1
3       Day_4        2            2         1     0
4       Day_5        2            2         0     1
..        ...      ...          ...       ...   ...
995   Day_996        2            2         0     1
996   Day_997        0            2         0     0
997   Day_998        1            2         0     0
998   Day_999        0            0         1     0
999  Day_1000        1            2         1     1

[1000 rows x 5 columns]

In [83]:
y

0      1
1      1
2      1
3      1
4      0
      ..
995    0
996    1
997    0
998    1
999    1
Name: PlayTennis, Length: 1000, dtype: int64

In [84]:
## Splitting dataset horizontally (train & test set(20%) )
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [85]:
## Using Decision tree model
from sklearn.tree import DecisionTreeClassifier
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

dt=DecisionTreeClassifier()

In [86]:
dt

DecisionTreeClassifier()

In [87]:
## training the data model 
# Day ID is a string identifier not a model feature

x_train=x_train.drop(columns=['Day ID'])
x_test =x_test.drop(columns=['Day ID'])

In [88]:
predict=dt.predict

In [89]:
dt.fit(x_train, y_train)
pred = dt.predict(x_test)

In [90]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        69
           1       1.00      1.00      1.00       131

    accuracy                           1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200